In [18]:
import get_census
import pandas as pd

In [19]:
census = get_census.DataPlan("test_vars.yml", geometry="county")
census.assemble_data()

2000 hispanic_pct
2000 poverty
2000 poverty_mcare
2009 hispanic_pct
2009 poverty
2009 poverty_mcare
2010 hispanic_pct
2010 poverty
2010 poverty_mcare
2011 hispanic_pct
2011 poverty
2011 poverty_mcare
2012 hispanic_pct
2012 poverty
2012 poverty_mcare
2013 hispanic_pct
2013 poverty
2013 poverty_mcare
2014 hispanic_pct
2014 poverty
2014 poverty_mcare
2015 hispanic_pct
2015 poverty
2015 poverty_mcare
2016 hispanic_pct
2016 poverty
2016 poverty_mcare
2017 hispanic_pct
2017 poverty
2017 poverty_mcare
2018 hispanic_pct
2018 poverty
2018 poverty_mcare
2019 hispanic_pct
2019 poverty
2019 poverty_mcare


In [37]:
roll_test = census.data.copy()

In [38]:
roll_test['geoid'] = roll_test['state'] + roll_test['county']
print(roll_test)

      state county  year  hispanic_pct   poverty  poverty_mcare  geoid
0        05    069  2000      0.009611  0.205307       0.178257  05069
1        13    031  2000      0.018791  0.244940       0.186392  13031
2        17    127  2000      0.008113  0.134925       0.141077  17127
3        20    053  2000      0.035862  0.072031       0.110827  20053
4        22    115  2000      0.059222  0.152549       0.148036  22115
...     ...    ...   ...           ...       ...            ...    ...
38639    47    033  2019      0.105632  0.178286       0.090728  47033
38640    47    095  2019      0.023240  0.285683       0.101925  47095
38641    47    093  2019      0.042739  0.145423       0.085663  47093
38642    53    005  2019      0.216937  0.119284       0.064427  53005
38643    53    011  2019      0.096202  0.092571       0.072467  53011

[38644 rows x 7 columns]


state county  year  hispanic_pct   poverty  poverty_mcare  geoid
0        05    069  2000      0.009611  0.205307       0.178257  05069
1        13    031  2000      0.018791  0.244940       0.186392  13031
2        17    127  2000      0.008113  0.134925       0.141077  17127
3        20    053  2000      0.035862  0.072031       0.110827  20053
4        22    115  2000      0.059222  0.152549       0.148036  22115
...     ...    ...   ...           ...       ...            ...    ...
36689    20    053  2019      0.061627  0.092861       0.104527  20053
37105    22    115  2019      0.092998  0.172544       0.140481  22115
37459    37    097  2019      0.076257  0.109242       0.069427  37097
38236    31    057  2019      0.118139  0.105769       0.041237  31057
38360    28    051  2019      0.001691  0.423522       0.253129  28051

[120 rows x 7 columns]

In [41]:
test = pd.DataFrame([[x, y] for x in range(1999, 2020) for y in roll_test.geoid.unique()], columns=['year','geoid'])

In [42]:
test

year  geoid
0      1999  05069
1      1999  13031
2      1999  17127
3      1999  20053
4      1999  22115
...     ...    ...
67762  2019  02230
67763  2019  02275
67764  2019  08014
67765  2019  02158
67766  2019  46102

[67767 rows x 2 columns]

In [43]:
roll_test = pd.merge(test, roll_test, how="left", on=['year','geoid'])
roll_test

year  geoid state county  hispanic_pct   poverty  poverty_mcare
0      1999  05069   NaN    NaN           NaN       NaN            NaN
1      1999  13031   NaN    NaN           NaN       NaN            NaN
2      1999  17127   NaN    NaN           NaN       NaN            NaN
3      1999  20053   NaN    NaN           NaN       NaN            NaN
4      1999  22115   NaN    NaN           NaN       NaN            NaN
...     ...    ...   ...    ...           ...       ...            ...
67762  2019  02230    02    230      0.056911  0.063752       0.015385
67763  2019  02275    02    275      0.050360  0.078289       0.010791
67764  2019  08014    08    014      0.123796  0.055708       0.036052
67765  2019  02158    02    158      0.011273  0.390110       0.202643
67766  2019  46102    46    102      0.040809  0.461728       0.311715

[67767 rows x 7 columns]

In [28]:
with_missing = np.array(roll_test[roll_test.geoid == "22115"]['poverty'])

In [29]:
with_missing

array([       nan, 0.1525486 ,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
       0.16631173, 0.14975785, 0.13985056, 0.1264897 , 0.13497411,
       0.13189453, 0.14724134, 0.14497194, 0.16869036, 0.17152842,
       0.17254421])

In [47]:
import math
import numpy as np
np.nanmean([4, 5, np.nan, 7])

5.333333333333333

In [68]:
with_missing[range(2,7)]

array([nan, nan, nan, nan, nan])

In [52]:
with_missing[0:7]

array([       nan, 0.10489214,        nan,        nan,        nan,
              nan,        nan])

In [71]:
x = with_missing.copy()
x[4] = 69
x

array([        nan,  0.10489214,         nan,         nan, 69.        ,
               nan,         nan,         nan,         nan,         nan,
        0.12396077,  0.14652865,  0.14102797,  0.15280817,  0.15328267,
        0.15692392,  0.15924153,  0.15519779,  0.15380308,  0.15937149,
        0.1636176 ])

In [61]:
x[np.argwhere(np.isnan(x))] = 0
x
np.sum(x)

70.77065577212673

In [66]:
not np.isnan(69)

True

In [70]:
x[np.array(range(2,5)) - 1]

array([0.10489214, 0.        , 0.        ])

In [1]:
import nsaph_utils

In [2]:
import numpy as np
import math
import random

In [3]:
x = np.array([1.0  + i for i in range(100)])

In [4]:
x[10:20] = np.nan

In [5]:
indices = nsaph_utils.get_indices(x, 18, 1)
window = x[indices]
window[np.argwhere(np.isnan(window))] = 0

In [6]:
weights = nsaph_utils.calc_weights(x, indices, 18)

In [7]:
window.dot(weights) / np.sum(weights)

21.333333333333332

In [8]:
x

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [17]:
nsaph_utils.interpolate_ma(x[10:21], 1)

array([21., 21., 21., 21., 21., 21., 21., 21., 21., 21., 21.])

In [30]:
nsaph_utils.interpolate_ma(with_missing, 4)

array([0.15257542, 0.1525486 , 0.15265529, 0.15296566, 0.15407783,
       0.15713631, 0.15873247, 0.16079377, 0.15780188, 0.1557144 ,
       0.16631173, 0.14975785, 0.13985056, 0.1264897 , 0.13497411,
       0.13189453, 0.14724134, 0.14497194, 0.16869036, 0.17152842,
       0.17254421])

In [34]:
chosen_counties
census.plan.keys()

dict_keys([2000, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019])

In [44]:
saved = roll_test.copy()

for county in roll_test.geoid.unique():
    for var in ['hispanic_pct', 'poverty']:
        roll_test.loc[roll_test.geoid == county, var + "_int"] = nsaph_utils.interpolate_ma(roll_test[roll_test.geoid == county][var], 4)

roll_test

year  geoid state county  hispanic_pct   poverty  poverty_mcare  \
0      1999  05069   NaN    NaN           NaN       NaN            NaN   
1      1999  13031   NaN    NaN           NaN       NaN            NaN   
2      1999  17127   NaN    NaN           NaN       NaN            NaN   
3      1999  20053   NaN    NaN           NaN       NaN            NaN   
4      1999  22115   NaN    NaN           NaN       NaN            NaN   
...     ...    ...   ...    ...           ...       ...            ...   
67762  2019  02230    02    230      0.056911  0.063752       0.015385   
67763  2019  02275    02    275      0.050360  0.078289       0.010791   
67764  2019  08014    08    014      0.123796  0.055708       0.036052   
67765  2019  02158    02    158      0.011273  0.390110       0.202643   
67766  2019  46102    46    102      0.040809  0.461728       0.311715   

       hispanic_pct_int  poverty_int  
0              0.009622     0.205339  
1              0.018807     0.244967  
2              0.008124     0.134954  
3              0.035881     0.072061  
4              0.059271     0.152575  
...                 ...          ...  
67762          0.056911     0.063752  
67763          0.050360     0.078289  
67764          0.123796     0.055708  
67765          0.011273     0.390110  
67766          0.040809     0.461728  

[67767 rows x 9 columns]

In [46]:
roll_test[roll_test.geoid == "05069"]

year  geoid state county  hispanic_pct   poverty  poverty_mcare  \
0      1999  05069   NaN    NaN           NaN       NaN            NaN   
3227   2000  05069    05    069      0.009611  0.205307       0.178257   
6454   2001  05069   NaN    NaN           NaN       NaN            NaN   
9681   2002  05069   NaN    NaN           NaN       NaN            NaN   
12908  2003  05069   NaN    NaN           NaN       NaN            NaN   
16135  2004  05069   NaN    NaN           NaN       NaN            NaN   
19362  2005  05069   NaN    NaN           NaN       NaN            NaN   
22589  2006  05069   NaN    NaN           NaN       NaN            NaN   
25816  2007  05069   NaN    NaN           NaN       NaN            NaN   
29043  2008  05069   NaN    NaN           NaN       NaN            NaN   
32270  2009  05069    05    069      0.015408  0.222194       0.133575   
35497  2010  05069    05    069      0.015742  0.225944       0.125576   
38724  2011  05069    05    069      0.015909  0.228623       0.134295   
41951  2012  05069    05    069      0.016086  0.232751       0.137341   
45178  2013  05069    05    069      0.016759  0.239005       0.144028   
48405  2014  05069    05    069      0.017775  0.245158       0.121529   
51632  2015  05069    05    069      0.018695  0.254666       0.129145   
54859  2016  05069    05    069      0.018913  0.255015       0.127416   
58086  2017  05069    05    069      0.019755  0.247091       0.133480   
61313  2018  05069    05    069      0.020334  0.231870       0.122999   
64540  2019  05069    05    069      0.021001  0.222007       0.144666   

       hispanic_pct_int  poverty_int  
0              0.009622     0.205339  
3227           0.009611     0.205307  
6454           0.009656     0.205437  
9681           0.009787     0.205818  
12908          0.010255     0.207183  
16135          0.011543     0.210936  
19362          0.014042     0.218910  
22589          0.015520     0.223444  
25816          0.015575     0.224184  
29043          0.015609     0.224755  
32270          0.015408     0.222194  
35497          0.015742     0.225944  
38724          0.015909     0.228623  
41951          0.016086     0.232751  
45178          0.016759     0.239005  
48405          0.017775     0.245158  
51632          0.018695     0.254666  
54859          0.018913     0.255015  
58086          0.019755     0.247091  
61313          0.020334     0.231870  
64540          0.021001     0.222007